#Use Movies Tonight
USE MoviesTonight;
#Inserting data into MOVIE with MTitle and Rating
INSERT INTO MOVIE (Title, Rating)
SELECT DISTINCT MTitle, Rating
FROM DATASHEET;

INSERT INTO THEATER (`TNAME`, `Location`, `Showtime`)
SELECT DISTINCT TName, Location, Phone
FROM DATASHEET;

INSERT INTO ARTIST (`ArtistID`)
SELECT DISTINCT CCode
FROM DATASHEET;

#Inserting data into SHOWS
INSERT INTO `SHOWS` (`Showtime`, `MovieID`, `TheaterID`)
	SELECT DISTINCT ShowTime, MOVIE.MovieID, THEATER.TheaterID
	FROM MOVIE JOIN DATASHEET ON (MOVIE.Title = DATASHEET.MTitle)
		       JOIN THEATER ON (`DATASHEET`.`TName` = `THEATER`.`TNAME`)
SELECT * FROM `SHOWS`;

INSERT INTO `CREDIT` (`CCODE`, `ArtistID`, `MovieID`)
	SELECT DISTINCT  CCode, ARTIST.ArtistID, MOVIE.MovieID
    FROM CREDIT JOIN DATASHEET ON (ARTIST.CCode, DATASHEET.CCODE)
				JOIN MOVIE ON (`DATASHEET`.`MTitle` = `MOVIE`.`Title`)
SELECT * FROM `CREDIT`